# Generated by Django 6.0 on 2026-02-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_status_application_status_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='match_score',
        ),
    ]
