# Generated by Django 6.0 on 2026-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_cv_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
