# Generated by Django 6.0 on 2026-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_cv_analysis_cv_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='roadmap',
            field=models.TextField(blank=True),
        ),
    ]
