# Generated by Django 6.0 on 2026-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_cv_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='roadmap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
